#!/bin/sh
# Builds TrimFast and packs it as a Haiku package (.hpkg). Run this ON Haiku:
#
#   packaging/haiku/build_hpkg.sh
#   LICENSE=MIT PACKAGER="Name <mail@example.org>" REVISION=2 packaging/haiku/build_hpkg.sh
#
# LICENSE is required: the project's licence is the author's decision, and a Haiku package
# must carry the licence text. Give the name of one of Haiku's standard licences (the text is
# taken from /boot/system/data/licenses/, e.g. MIT, "GNU GPL v3", "Apache 2.0"), or put the
# project's own text in a file named LICENSE at the top of the source tree and give any name.
#
# Needs: cmake, g++, qt6_base_devel, qt6_multimedia_devel (see README.md).
# Output: <build dir>/TrimFast-<version>-<revision>-<arch>.hpkg
set -e

if [ "$(uname -s)" != "Haiku" ]; then
    echo "This script builds a Haiku package and must run on Haiku." >&2
    exit 1
fi

here="$(cd "$(dirname "$0")" && pwd)"
cd "$here/../.."

version="$(sed -n 's/^project(TrimFast VERSION \([0-9][0-9.]*\).*/\1/p' CMakeLists.txt)"
[ -n "$version" ] || { echo "cannot read the version from CMakeLists.txt" >&2; exit 1; }
if [ -z "$LICENSE" ]; then
    echo "Set LICENSE=<licence name> (the licence is the author's decision; see the header of this script)." >&2
    exit 1
fi
revision="${REVISION:-1}"
arch="$(getarch)"
packager="${PACKAGER:-Michihiko Mikami}"
license="$LICENSE"
build="${BUILD_DIR:-build-hpkg}"
jobs="${JOBS:-3}" # make -j8 can stall a small VM

echo "== Building TrimFast $version ($arch)"
cmake -S . -B "$build" -DCMAKE_BUILD_TYPE=Release -DTRIMFAST_BUILD_TESTS=OFF
cmake --build "$build" -j"$jobs"

echo "== Staging"
stage="$build/package-root"
rm -rf "$stage"
mkdir -p "$stage/apps" "$stage/bin" "$stage/data/deskbar/menu/Applications" \
         "$stage/documentation/packages/trimfast"
cp "$build/trimfast" "$stage/apps/TrimFast"
strip --strip-unneeded "$stage/apps/TrimFast"

# Application resources (signature, version info) and the MIME database entry.
# (trimfast_icon.rdef is generated by make_icon.py from the drawing in that script.)
rc -o "$build/trimfast.rsrc" "$here/trimfast.rdef" "$here/trimfast_icon.rdef"
xres -o "$stage/apps/TrimFast" "$build/trimfast.rsrc"
mimeset -f "$stage/apps/TrimFast"

# `trimfast` on the command line, and the Deskbar's Applications menu.
ln -s ../apps/TrimFast "$stage/bin/trimfast"
ln -s ../../../../apps/TrimFast "$stage/data/deskbar/menu/Applications/TrimFast"

# The licence text (Haiku refuses a package whose licences are not contained in it).
mkdir -p "$stage/data/licenses"
if [ -f LICENSE ]; then
    cp LICENSE "$stage/data/licenses/$license"
elif [ -f "/boot/system/data/licenses/$license" ]; then
    cp "/boot/system/data/licenses/$license" "$stage/data/licenses/$license"
else
    echo "No licence text: put it in ./LICENSE or use a name from /boot/system/data/licenses." >&2
    exit 1
fi

cp README.md CHANGELOG.md "$stage/documentation/packages/trimfast/"
cp docs/manual_test_checklist.md "$stage/documentation/packages/trimfast/"

sed -e "s|@VERSION@|$version|g" -e "s|@REVISION@|$revision|g" -e "s|@ARCH@|$arch|g" \
    -e "s|@PACKAGER@|$packager|g" -e "s|@LICENSE@|$license|g" \
    "$here/PackageInfo.in" > "$build/PackageInfo"

echo "== Packing"
out="$build/TrimFast-$version-$revision-$arch.hpkg"
rm -f "$out"
package create -C "$stage" -i "$build/PackageInfo" "$out"
package list "$out"
echo
package info "$out"
echo "== Done: $out"
